#!/usr/bin/env python3
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


SITE_DIR = Path("site")
SITE_INDEX = SITE_DIR / "index.html"


def render_html(generated_at: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>SSO Experimental Stand Report</title>
  <style>
    :root {{
      --bg: #f5f7fb;
      --text: #101828;
      --muted: #475467;
      --border: #d0d5dd;
      --card: #ffffff;
      --ok: #067647;
      --warn: #b54708;
      --na: #344054;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.45;
    }}
    .container {{
      max-width: 1100px;
      margin: 0 auto;
      padding: 28px 18px 42px;
    }}
    .card {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 18px;
      margin-bottom: 16px;
    }}
    h1, h2 {{
      margin: 0 0 10px;
      line-height: 1.2;
    }}
    p {{
      margin: 0 0 10px;
      color: var(--muted);
    }}
    .note {{
      border-left: 4px solid #155eef;
      padding: 10px 12px;
      background: #eef4ff;
      border-radius: 8px;
      color: #004eeb;
      font-weight: 600;
    }}
    ul {{
      margin: 8px 0 0;
      padding-left: 18px;
    }}
    li {{ margin: 4px 0; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
      font-size: 14px;
    }}
    th, td {{
      border: 1px solid var(--border);
      padding: 8px 10px;
      vertical-align: top;
      text-align: left;
    }}
    thead th {{
      background: #f2f4f7;
    }}
    .ok {{ color: var(--ok); font-weight: 600; }}
    .warn {{ color: var(--warn); font-weight: 600; }}
    .na {{ color: var(--na); font-weight: 600; }}
    .footer {{
      margin-top: 10px;
      color: #667085;
      font-size: 13px;
    }}
    code {{
      background: #eef2ff;
      border: 1px solid #c7d7fe;
      border-radius: 6px;
      padding: 1px 6px;
      font-size: 13px;
      color: #1d4ed8;
    }}
  </style>
</head>
<body>
  <main class="container">
    <section class="card">
      <h1>SSO Experimental Stand: Security Report</h1>
      <p>This page is a custom one-page report generated by CI and published to GitHub Pages.</p>
      <p class="note">Each profile has two modes: <strong>vulnerable</strong> (intentionally weak protection) and <strong>hardened</strong> (security best practices enabled).</p>
    </section>

    <section class="card">
      <h2>1. What This Stand Is</h2>
      <p>The stand compares three SSO-related architecture profiles under controlled attack simulations to demonstrate how insecure and hardened configurations behave under the same conditions.</p>
    </section>

    <section class="card">
      <h2>2. What Is Tested (Profiles)</h2>
      <ul>
        <li><strong>Profile A:</strong> Go app + Keycloak (OIDC/OAuth2 + PKCE).</li>
        <li><strong>Profile B:</strong> Go app with direct WebAuthn/FIDO2 passkeys.</li>
        <li><strong>Profile C:</strong> Go app + Vaultwarden backend, session-based auth gateway.</li>
      </ul>
    </section>

    <section class="card">
      <h2>3. Attack Vectors Covered</h2>
      <ul>
        <li>Brute force and credential stuffing.</li>
        <li>Phishing-origin checks (WebAuthn).</li>
        <li>Token replay, JWT alg:none, and session hijacking checks.</li>
        <li>OAuth redirect URI and CSRF/state/PKCE checks.</li>
        <li>IdP SPOF, DB/secret leak checks, and security headers audit.</li>
      </ul>
    </section>

    <section class="card">
      <h2>4. Results (Profile Summary)</h2>
      <table>
        <thead>
          <tr>
            <th>Attack</th>
            <th>Profile A</th>
            <th>Profile B</th>
            <th>Profile C</th>
          </tr>
        </thead>
        <tbody>
          <tr><td>A1 Brute Force</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no password)</td><td class="warn">⚠️ vuln/hard</td></tr>
          <tr><td>A2 Credential Stuffing</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no password)</td><td class="warn">⚠️ vuln/hard</td></tr>
          <tr><td>A3 Phishing (WebAuthn)</td><td class="na">❌ N/A</td><td class="ok">✅ architecture-protected</td><td class="na">❌ N/A</td></tr>
          <tr><td>B1 Token Replay</td><td class="warn">⚠️ vuln/hard</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no JWT in this flow)</td></tr>
          <tr><td>B2 JWT alg:none</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no JWT)</td><td class="na">❌ N/A (no JWT)</td></tr>
          <tr><td>B3 Session Hijacking</td><td class="warn">⚠️ vuln/hard</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (not covered by current A6 path)</td></tr>
          <tr><td>C1 redirect_uri</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no OAuth)</td><td class="na">❌ N/A (no OAuth)</td></tr>
          <tr><td>C2 CSRF/state</td><td class="warn">⚠️ vuln/hard</td><td class="na">❌ N/A (no OAuth)</td><td class="na">❌ N/A (no OAuth)</td></tr>
          <tr><td>D1 IdP SPOF</td><td class="warn">⚠️ SPOF in both variants</td><td class="ok">✅ independent from Keycloak</td><td class="na">❌ N/A (not Keycloak-dependent)</td></tr>
          <tr><td>D2 DB Leak</td><td class="warn">⚠️ vuln/hard (different severity)</td><td class="na">❌ N/A (no DB in current test path)</td><td class="warn">⚠️ vuln/hard</td></tr>
          <tr><td>E1 Security Headers</td><td class="warn">⚠️ vuln/hard</td><td class="warn">⚠️ vuln/hard</td><td class="warn">⚠️ vuln/hard</td></tr>
        </tbody>
      </table>
      <p class="footer">Generated in CI: {generated_at}</p>
    </section>

    <section class="card">
      <h2>5. Mitigation and Best Practices</h2>
      <ul>
        <li>Use strict rate limiting and lockout policies for authentication endpoints.</li>
        <li>Enforce PKCE (S256), strict <code>state</code> validation, and exact redirect URI allowlists.</li>
        <li>Harden sessions and cookies: <code>HttpOnly</code>, <code>Secure</code>, <code>SameSite</code>, server-side invalidation.</li>
        <li>Validate JWT algorithms explicitly and reject unsigned or downgraded tokens.</li>
        <li>Apply baseline response headers: HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy.</li>
        <li>Reduce SPOF risk with HA IdP topology and failover strategy.</li>
      </ul>
    </section>
  </main>
</body>
</html>
"""


def main() -> None:
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    SITE_INDEX.write_text(render_html(generated_at), encoding="utf-8")
    print(f"Written {SITE_INDEX}")


if __name__ == "__main__":
    main()
